name: Build

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
    # Création des artifacts
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Build binaries for all platforms
      run: make build cross-platform 
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: Release
        owner: anotherhope
        tag: latest
        body: Release
        artifacts: #Source artifacts ".build/bin/*"
        allowUpdates: true
        replacesArtifacts: true
        removeArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: deploy/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: # Repository Name
